on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+-preview\d{1,3}'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack -c Release Typeform/Typeform.csproj /p:Version=${VERSION} -p:NuspecFile=Typeform.nuspec --output .
    - name: Push
      run: dotnet nuget push Typeform.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}